language: node_js

node_js:
  - "14"
sudo: false
script: npm run $COMMAND

env:
  matrix:
  - COMMAND=test
  - CLIENT=selenium:phantomjs COMMAND=test
  - COMMAND=coverage

branches:
  only:
  - master
